###############################################################
# ~~ Secret values for both wordpress frontend and backend ~~ #

# Use 'ansible-vault encrypt group_vars/secrets.yml'
# To keep your secrets safe
# https://docs.ansible.com/ansible/latest/user_guide/vault.html#encrypting-unencrypted-files

db_root_password: mySuperSecretPassword
db_host: wordpress-mysql
db_name: db-wordpress
db_user: wordpress
db_password: myAwesomeSecret
wp_user: dysonfrost
wp_password: pleasechangeme
wp_email: jeremy.reisser@gmail.com
