###############################################################
# ~~ Secret values for both wordpress frontend and backend ~~ #

# Use 'ansible-vault encrypt group_vars/secrets.yml'
# To keep your secrets safe
# https://docs.ansible.com/ansible/latest/user_guide/vault.html#encrypting-unencrypted-files

db_root_password: mySuperSecretPasswordL0uPo$aylouposay
db_host: wordpress-mysql
db_name: db-wordpress
db_user: wordpress
db_password: myAwesomeSecretL0uPo$aylouposay
wp_user: dysonfrost
wp_password: L0uPo$aylouposay
wp_email: jeremy.reisser@gmail.com
