- name: Create IAM role for external-dns
  iam_role:
    name: "{{ externaldns_role_name }}"
    assume_role_policy_document: "{{ lookup('file','{{ trust_policy }}') }}"
    profile: "{{ aws_profile }}"

- name: Attach external-dns policy to the above role
  iam_policy:
    iam_type: role
    iam_name: "{{ externaldns_role_name }}"
    policy_name: "{{ externaldns_role_name }}"
    state: present
    policy_document: "{{ playbook_dir }}/policies/{{ externaldns_policy }}"
    profile: "{{ aws_profile }}"

- name: Deploy external-dns using kubectl
  command: "kubectl apply -f -"
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'external-dns.yml.j2') }}"
